#
# OriginPHP Framework
# Copyright 2018 - 2021 Jamiel Sharief.
#
# Licensed under The MIT License
# The above copyright notice and this permission notice shall be included in all copies or substantial
# portions of the Software.
#
# @copyright    Copyright (c) Jamiel Sharief
# @link         https://www.originphp.com
# @license      https://opensource.org/licenses/mit-license.php MIT License
#
# Note:
# MySQL, Postgres, Minio and Elastic search have their own volumes, so when enabling or disabling services remember
# to check the volumes section at the bottom of the file.
version: "3"
services:
  app:
    build: .
    ports:
      - "443:443"
    volumes:
      - .:/var/www
    depends_on:
      - db
    links:
      - "db"
  db:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
  redis:
    image: redis
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
  #  db:
  #    image: postgres:12.5
  #    volumes:
  #      - pg-data:/var/lib/postgresql/data
  #    environment:
  #      POSTGRES_USER: root
  #      POSTGRES_PASSWORD: root
  #    ports:
  #      - "5432:5432"
  #  db:
  #    image: mariadb
  #    restart: always
  #    environment:
  #      MYSQL_ROOT_PASSWORD: root
  #    ports:
  #      - "3306:3306"
  #    volumes:
  #      - mysql-data:/var/lib/mysql
  #  minio:
  #    image: minio/minio
  #    volumes:
  #      - minio-data:/data
  #    ports:
  #      - "9000:9000"
  #    environment:
  #      MINIO_ACCESS_KEY: minio
  #      MINIO_SECRET_KEY: b1816172fd2ba98f3af520ef572e3a47
  #    command: server /data
#  hoppscotch:
#    image: hoppscotch/hoppscotch
#    ports:
#      - 3000:3000
#  memcached:
#    image: memcached
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
#    container_name: elasticsearch
#    environment:
#      - discovery.type=single-node
#    volumes:
#      - es-data:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
volumes:
  mysql-data:
#  pg-data:
# minio-data:
# es-data:
#   driver: local

