version: "2.1"
services:
  app:
    depends_on:
      - db
    links:
      - "db"
    volumes:
      - .:/var/www
  db:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
volumes:
  mysql-data:
