version: '2.1'
services:
  app:
    depends_on:
      - db
    links:
      - "db"
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
  db:
    image: postgres:12.5
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "54320:5432"
volumes:
  pg-data: